### ISSUE TITLE
Undefined column error

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/indigo#26]
Selecting the Budget phase element on the Budget phase dimension throws an error

```
Error: undefined columns selected In call: `[.data.frame`(dt, variables) 
```

you can check [here](http://apps.openbudgets.eu/cube/analytics/budget-athens-expenditure-2006__97b39/descriptive_statistics/facts?amounts=amount&dimensions=budgetPhase.budgetPhase&json_data=http%3A%2F%2Fapps.openbudgets.eu%2Fapi%2F3%2Fcubes%2Fbudget-athens-expenditure-2006__97b39%2Ffacts%3Fpagesize%3D300)

**Comment by larjohn** [comment]
This was due to selecting attributes that are not existent in the requested subset of data. A new property (bound) has been introduced and implemented in DAM and indigo so that it does not let you select such an attribute.

In due time, all inputs will have such restrictions.

You can view what I mean here:

http://apps.openbudgets.eu/cube/analytics/budget-athens-expenditure-2006__97b39/descriptive_statistics/facts

**Comment by skarampatakis** [comment]
It seems that I can still make the request with no complain [here](http://apps.openbudgets.eu/cube/analytics/budget-athens-expenditure-2006__97b39/descriptive_statistics/facts?amounts=amount&dimensions=budgetPhase.budgetPhase&json_data=http%3A%2F%2Fapps.openbudgets.eu%2Fapi%2F3%2Fcubes%2Fbudget-athens-expenditure-2006__97b39%2Ffacts%3Fpagesize%3D300)

However it is hidden from the indigo GUI.

**Comment by larjohn** [comment]
You are not supposed/expected to craft arbitrary request URLs while using the GUI.

You do get an error message although not that friendly. Do you think @kleanthisk10 should provide sth else?

**Comment by skarampatakis** [comment]
I think that the request should be cut before it reaches the computation server, with an appropriate error message. 

Also I think that these kind of errors should be handled by DAM, so there would be a unified handling. I mean that DAM should check for query validation and if it passes then it should send the request to the according algorithm server.
